POST http://localhost:8000/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "5 PLN",
  "additionalInfo": {
    "cardNumber": "1234567789",
    "cvv": 255
  }

}

###

GET http://localhost:8000/payments/fb6ff235-7a66-4fb5-9530-5e4e9a31e356
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8000/orders
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "entries": {
    "1": 2,
    "2": 5
  }
}

###

GET https://fullstack-developer.io/api-dev/products?_start=0&_limit=10

###

GET https://fullstack-developer.io/api-dev/products/count

###

POST https://fullstack-developer.io/api-dev/auth/local
Accept: application/json
Content-Type: application/json

{
  "identifier": "training@sages.pl",
  "password": "P@ssw0rd"
}

###

POST http://localhost:8081/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "100 PLN"
}



























