POST http://localhost:8080/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "5 PLN",
  "additionalInfo": {
    "cardNumber": "1234567789",
    "cvv": 255
  }

}

###

GET http://localhost:8080/payments/ffa22ae1-a159-4ebe-a0ec-53910683506b
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8080/orders
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "entries": {
    "1": 2,
    "2": 5
  }
}
