spring:
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/training
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.transaction: trace
    org.javamoney.moneta.FastMoney: OFF
api:
    products: https://fullstack-developer.io/api-dev/products
